packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # all packages that are inside test directories
  - 'packages/**/__tests__/**'
  # docs
  - 'docs'
  # server for back-end
  - 'nest-server'
  # client for front-end
  - example
