name: "PR-Lint"

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/shared-steps.yml
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: pnpm build # 构建指定应用
      - name: Lint
        run: pnpm lint # 检查指定应用的代码风格
